# Command-line arguments can override these values.

total_episodes: 5000
seed: 42

# Logging settings
logger: wandb # Options: tensorboard, wandb, both, console, none
log_dir: ./logs
wandb_project_name: dynaq
wandb_entity: null
record_period: 1000
log_interval_steps: 100

torch_deterministic: true
cuda: true
track: false

# Standard RL hyperparameters
learning_rate: 0.00025
buffer_size: 200000
gamma: 0.99
tau: 0.005
target_network_frequency: 200 # in training steps
batch_size: 64
start_e: 1.0
end_e: 0.05
exploration_fraction: 0.5
learning_starts_after_episode: 10
train_frequency: 1 # in training steps
updates_per_steps: 5updates_per_episode

# DynaQ-specific hyperparameters
imagined_buffer_size: 200000
model_learning_rate: 0.001
model_update_episodes: 5 # how many episodes to use to update the world model
dream_switch_off_episode: 200
dream_rollout_length: 2
dream_frequency: 10 # how often, in training steps, to generate dreams
dream_batch_size: 64
q_batch_ratio: 0.5
