# Command-line arguments can override these values.

total_episodes: 1500
seed: 1337

# Logging settings
logger: wandb # Options: tensorboard, wandb, both, console, none
log_dir: ./logs
wandb_project_name: dynaq
wandb_run_name: dqn8
wandb_entity: null
record_period: 500
log_interval_steps: 200

torch_deterministic: true
cuda: true
track: false

# Standard RL hyperparameters
learning_rate: 0.0005
buffer_size: 100000
gamma: 0.999
tau: 0.002
target_network_frequency: 200 # in training steps
batch_size: 64
epsilon_start: 1.0
epsilon_end: 0.01
epsilon_decay: 0.995
learning_starts_after_episode: 5
train_frequency: 4 # in training steps
updates_per_step: 1

# DynaQ-specific hyperparameters
imagined_buffer_size: 100000
model_learning_rate: 0.0005
model_update_episodes: 5 # how many episodes to use to update the world model
avg_episode_length: 400
dream_start_episode: 400
dream_switch_off_episode: 0
dream_rollout_length: 1
dream_frequency: 16 # how often, in training steps, to generate dreams
dream_batch_size: 16
q_batch_ratio: 0.5 # ratio of real to imagined samples in a training batch
